### ISSUE TITLE
[Question] How would I specify excluding as many Cuda related packages as possible

### ISSUE THREAD

**Issue by zoof** [conda-incubator/conda-mirror#72]
I have a config.yaml file that mirrors everything for Python 3.12:
```
blacklist:
  - name: "*"
whitelist:
  - build: "*py312*"
  - name: python
    version: ">=3.12.0"
include_depends: True
```
Is there some refinement to this possible that would exclude Cuda related packages?  I don't have ready access to machines with a discrete GPU and cudatoolkit in particular takes up a tremendous amount of space.

**Comment by zoof** [comment]
I believe I have solved this by specifying:
```
whitelist:
  - build: "*py312*"
  - name: cudatoolkit
    version: ">=100"
include_depends: True
```

**Comment by bilderbuchi** [comment]
NB: by trial and error I found that this only works if no other packages depend on `cudatoolkit`. Doing e.g.
```
blacklist:
  - name: "*"
  - name: "*pypy3*"
whitelist:
  - name: cudatoolkit
    version: ">=100"
  - name: python
    version: "=3.12"
  - name: pandas
    version: ">=2.2"
    build: "py312*"
  - name: numpy
    version: ">=2.0"
    build: "py312*"
  - name: mkl
    version: ">=2024"
include_depends: True
```
*Still* yields you a bunch of `cudatoolkit` packages, although your specification matches none of them.
