### ISSUE TITLE
Package versioning doesn't seem to be working

### ISSUE THREAD

**Issue by leemhmark** [conda-incubator/conda-mirror#74]
I'm not sure if this is a bug or I'm doing something wrong, but according to the documentation I should be able to restrict a version of a package I'm mirroring using this syntax in my config.yml:

whitelist:
- name: numpy
  version: ">2.1.0"

However when I ran a dry run all numpy versions from 1.11.3 and above showed up in the list of packages to be downloaded in INFO. I'm running the conda-mirror command as: 

`conda-mirror -vv --config config.yml --platform noarch --temp-directory [temp dir] --upstream-channel https://conda.anaconda.org/conda-forge --target-directory [target directory] --no-validate-target --include-depends --dry-run`

My config.yml is:

```
blacklist:
- name: "*"
channel_alias: https://repo.continuum.io/pkgs/
channels:
- conda-forge
repo-build:
  dependencies: true
  platforms:
  - win-64
root-dir: C:\repo
whitelist:
- name: numpy
  version: ">2.1.0"
```
